/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Control.Control;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author edva5
 */
public class InterfazLogIn extends myInterface implements Observer {
    public static final String LOGIN="MenuLogIn";
    public static final String ADMINISTRADOR="Administrador",ESTUDIANTE="Estudiante",MATRICULADOR="Matriculador";
    /**
     * @return the jCheckBoxs
     */
    public ArrayList<JCheckBox> getjCheckBoxs() {
        return jCheckBoxs;
    }
    
    private ArrayList<JCheckBox> jCheckBoxs;
    private ArrayList<JLabel> jLabels; 
    private JPasswordField jPasswordField;
    private JTextField IDTxtFld;
    private JButton logInBtn;
    /**
     * @return the modelo
     */
    public Modelo.Modelo getModelo() {
        return modelo;
    }

    /**
     * @param modelo the modelo to set
     */
    public void setModelo(Modelo.Modelo modelo) {
        this.modelo = modelo;
    }
    public void setControl(Control control) {
        super.control=control;
        logInBtn.addActionListener(control);
    }
    private Modelo.Modelo modelo;
    /**
     * Creates new form InterfazLogIn
     */
    public InterfazLogIn() {
        initComponents();
        this.setTitle(LOGIN);
        jCheckBoxs = new ArrayList<JCheckBox>();
        jCheckBoxs.add(new JCheckBox(ESTUDIANTE));
        jCheckBoxs.add(new JCheckBox(MATRICULADOR));
        jCheckBoxs.add(new JCheckBox(ADMINISTRADOR));
        jCheckBoxs.stream().forEach(x->this.add(x));
        jCheckBoxs.stream().forEach(x->x.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                getjCheckBoxs().stream().filter(y->x!=y).forEach(y->y.setSelected(false));
            }
        }));
        for (int i = 0; i < jCheckBoxs.size(); i++) {
            jCheckBoxs.get(i).setBounds(300, i*50, 150, 50);
        }
        jPasswordField = new JPasswordField();
        jPasswordField.setBounds(100, 50, 150, 25);
        this.add(jPasswordField);
        jLabels= new ArrayList<JLabel>();
        jLabels.add(new JLabel("Password"));
        jLabels.add(new JLabel("ID"));
        for (int i = 0; i < jLabels.size(); i++) {            
                    this.add(jLabels.get(i));
                    jLabels.get(i).setBounds(0, i*50, 100, 25);
        }
        IDTxtFld= new JTextField();
        this.add(IDTxtFld);
        IDTxtFld.setBounds(100, 0, 150, 25);
        logInBtn = new JButton("LogIn");
        logInBtn.setBounds(100, 100, 100, 25);
        this.add(logInBtn);
        this.jScrollPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
