/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Modelo.Modelo;
import Control.Control;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author edva5
 */
public class InterfazMenuAdministrador extends myInterface  {
    public static final String MENU_ADMINISTRADOR="Menu Administrador";
    private ArrayList<JButton> jButtons;   
    /**
     * Creates new form InterfazMenuAdministrador
     */
    public InterfazMenuAdministrador() {
        initComponents();
        this.setTitle(MENU_ADMINISTRADOR);
        jButtons=new ArrayList<JButton>();
       this.mntoAdministradorBtn.setText(InterfazAdministrador.MANTENIMIENTO_ADMINISTRADOR);
       jButtons.add(mntoAdministradorBtn);
       this.mntoCarreraBtn.setText(InterfazCarrera.MANTENIMIENTO_CARRERA);
       jButtons.add(mntoCarreraBtn);
       this.mntoCursoBtn.setText(InterfazCurso.MANTENIMIENTO_CURSO);
       jButtons.add(mntoCursoBtn);
       this.mntoGrupoBtn.setText(InterfazGrupo.MANTENIMIENTO_GRUPO);
       jButtons.add(mntoGrupoBtn);
       this.mntoMatriculadorBtn.setText(InterfazMatriculador.MANTENIMIENTO_MATRICULADOR);
       jButtons.add(mntoMatriculadorBtn);
       this.mntoNotaBtn.setText(InterfazNota.MANTENIMIENTO_NOTA);
       jButtons.add(mntoNotaBtn);
       this.mntoProfesorBtn.setText(Interfaz.InterfazProfesor.MANTENIMIENTO_PROFESOR);
       jButtons.add(mntoProfesorBtn);
    }

    @Override
    public void setControl(Control control) {
        super.setControl(control); //To change body of generated methods, choose Tools | Templates.
        jButtons.stream().forEach(x->x.addActionListener(control));
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mntoAdministradorBtn = new javax.swing.JButton();
        mntoCarreraBtn = new javax.swing.JButton();
        mntoCursoBtn = new javax.swing.JButton();
        mntoGrupoBtn = new javax.swing.JButton();
        mntoMatriculadorBtn = new javax.swing.JButton();
        mntoNotaBtn = new javax.swing.JButton();
        mntoProfesorBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mntoAdministradorBtn.setText(Interfaz.InterfazAdministrador.MANTENIMIENTO_ADMINISTRADOR);
        mntoAdministradorBtn.setText("jButton1");

        mntoCarreraBtn.setText("jButton1");

        mntoCursoBtn.setText("jButton1");

        mntoGrupoBtn.setText("jButton1");

        mntoMatriculadorBtn.setText("jButton1");

        mntoNotaBtn.setText("jButton1");

        mntoProfesorBtn.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mntoCarreraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mntoCursoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mntoNotaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mntoAdministradorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mntoMatriculadorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(229, 229, 229)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mntoGrupoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(mntoProfesorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mntoCarreraBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mntoNotaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mntoCursoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mntoAdministradorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mntoGrupoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mntoMatriculadorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mntoProfesorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mntoAdministradorBtn;
    private javax.swing.JButton mntoCarreraBtn;
    private javax.swing.JButton mntoCursoBtn;
    private javax.swing.JButton mntoGrupoBtn;
    private javax.swing.JButton mntoMatriculadorBtn;
    private javax.swing.JButton mntoNotaBtn;
    private javax.swing.JButton mntoProfesorBtn;
    // End of variables declaration//GEN-END:variables
}
