/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Control.Control;
import Modelo.Modelo;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edva5
 */
public class myInterface extends javax.swing.JFrame {



    /**
     * @return the defaultTableModel
     */    
    protected Control control;
    protected Modelo modelo;
    protected JTable jTable;
    protected DefaultTableModel defaultTableModel;    
    protected JScrollPane jScrollPane;    
    //protected ButtonColumn saveButtonColumn;
    protected ButtonColumn deleteButtonColumn;
    public static JOptionPane jOptionPane;
    /**
     * Creates new form Interfaz
     */
    public myInterface() {
        initComponents();
        atrasBtn= new JButton("Atras");
        jTable= new JTable();
        jScrollPane= new JScrollPane(jTable);
        defaultTableModel=(DefaultTableModel) jTable.getModel();       
        
        this.add(jScrollPane);
        jScrollPane.setVisible(true);
        jScrollPane.setBounds(50, 50, 600, 250);
        this.setBounds(0, 0, 800, 500);                
    }
    public void addButtonsToTable(){
        
        defaultTableModel.addColumn("Eliminar");        
        deleteButtonColumn = new ButtonColumn(jTable, defaultTableModel.getColumnCount()-1, null, "Eliminar");
        //saveButtonColumn.setControl(control);
    }
    /**
     * @param control the control to set
     */
    public void setControl(Control control) {
        this.control = control;
        atrasBtn.addActionListener(control);
    }

    /**
     * @param modelo the modelo to set
     */
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    /**
     *
     * @return
     */
    public DefaultTableModel getDefaultTableModel() {
        return defaultTableModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atrasBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atrasBtn.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 341, Short.MAX_VALUE)
                .addComponent(atrasBtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 277, Short.MAX_VALUE)
                .addComponent(atrasBtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasBtn;
    // End of variables declaration//GEN-END:variables
}
